name: CI




on:
  pull_request:
    branches:
      - main



jobs:
 build-and-test: 
  name: Bygg och testa
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install dotnet
      uses: actions/setup-dotnet@v6
      with:
       dotnet-version: '10.0.x'

    - name: Setup dotnet
      run: |
        dotnet restore
        dotnet build --no-restore --configuration Release
        dotnet test --no-build --configuration Release
        
      
    
